# render.yaml
services:
  - type: web
    name: todo-api
    runtime: dotnet
    repo: https://github.com/seifmthabet/TodoAPI-.NET-
    branch: main
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/TodoAPI.dll
    envVars:
      - key: Jwt__Key
        value: 9R3+jvF9jZKo3qH7E8qLhr1A0gqVTL9UQOmYydYQ7Rk=